M48
; DRILL file {KiCad 6.0.11+dfsg-1} date mar 05 ago 2025 12:34:47
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-05T12:34:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.675Y-3.625
X3.675Y-4.425
X7.85Y-3.625
X7.85Y-4.425
T0
M30
